# Generated by Django 4.2.7 on 2025-08-03 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_nodes', models.PositiveIntegerField(default=0)),
                ('total_edges', models.PositiveIntegerField(default=0)),
                ('average_degree', models.FloatField(default=0.0)),
                ('clustering_coefficient', models.FloatField(default=0.0)),
                ('diameter', models.PositiveIntegerField(default=0)),
                ('density', models.FloatField(default=0.0)),
                ('influential_agents', models.JSONField(default=list)),
                ('community_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'network_analysis',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_agents', models.PositiveIntegerField(default=0)),
                ('active_agents', models.PositiveIntegerField(default=0)),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_follows', models.PositiveIntegerField(default=0)),
                ('posts_created_today', models.PositiveIntegerField(default=0)),
                ('likes_given_today', models.PositiveIntegerField(default=0)),
                ('comments_made_today', models.PositiveIntegerField(default=0)),
                ('follows_created_today', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmergentPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('viral_content', 'Viral Content'), ('echo_chamber', 'Echo Chamber'), ('influencer_emergence', 'Influencer Emergence'), ('trend_formation', 'Trend Formation'), ('community_formation', 'Community Formation'), ('behavioral_clustering', 'Behavioral Clustering')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_agents', models.ManyToManyField(blank=True, to='agents.aiagent')),
                ('related_posts', models.ManyToManyField(blank=True, to='content.post')),
            ],
            options={
                'db_table': 'emergent_patterns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('posts_created', models.PositiveIntegerField(default=0)),
                ('likes_given', models.PositiveIntegerField(default=0)),
                ('comments_made', models.PositiveIntegerField(default=0)),
                ('follows_created', models.PositiveIntegerField(default=0)),
                ('followers_gained', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='agents.aiagent')),
            ],
            options={
                'db_table': 'agent_behaviors',
                'ordering': ['-date'],
                'unique_together': {('agent', 'date')},
            },
        ),
    ]
