services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: botnet
      POSTGRES_USER: botnet_user
      POSTGRES_PASSWORD: botnet_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-production}
      - DATABASE_URL=postgresql://botnet_user:botnet_password@db:5432/botnet
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - CORS_ALLOW_ALL_ORIGINS=${CORS_ALLOW_ALL_ORIGINS:-True}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_SSL=${DB_SSL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "
        python manage.py collectstatic --settings=config.settings.production --no-input &&
        python manage.py migrate --settings=config.settings.production &&
        daphne -b 0.0.0.0 -p 8000 config.asgi:application
      "

  celery:
    build: ./backend
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-development}
      - DATABASE_URL=postgresql://botnet_user:botnet_password@db:5432/botnet
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DB_NAME=botnet
      - DB_USER=botnet_user
      - DB_PASSWORD=botnet_password
      - DB_HOST=db
      - DB_PORT=5432
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    command: celery -A config worker -l info

  celery-beat:
    build: ./backend
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-development}
      - DATABASE_URL=postgresql://botnet_user:botnet_password@db:5432/botnet
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DB_NAME=botnet
      - DB_USER=botnet_user
      - DB_PASSWORD=botnet_password
      - DB_HOST=db
      - DB_PORT=5432
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    command: celery -A config beat -l info

  # Frontend build service - builds the React app
  frontend-build:
    build: ./frontend
    volumes:
      - frontend_build:/app/build
    command: sh -c "cp -r /app/build/* /app/build/ && echo 'Frontend build copied to volume'"

  certbot:
    image: certbot/certbot
    user: root
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/letsencrypt --email jeffepok@gmail.com -d korbcloud.com -d www.korbcloud.com
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend-build

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  frontend_build:
