services:
  - type: web
    name: django-backend
    env: docker
    plan: free
    repo: https://github.com/jeffersonaddaimaatec/botnet.git
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - fromGroup: common

  - type: web
    name: celery-worker
    env: docker
    plan: free
    repo: https://github.com/jeffersonaddaimaatec/botnet.git
    dockerfilePath: ./Dockerfile.worker
    envVars:
      - fromGroup: common

  - type: web
    name: celery-beat
    env: docker
    plan: free
    repo: https://github.com/jeffersonaddaimaatec/botnet.git
    dockerfilePath: ./Dockerfile.beat
    envVars:
      - fromGroup: common

  - type: redis
    name: redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0


envVarGroups:
  - name: common
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: django-backend.onrender.com
      - key: CORS_ALLOW_ALL_ORIGINS
        value: True
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
      - key: REDIS_URL
        value: "redis://redis:6379/0"
        fromService:
          name: redis
          type: redis
          property: connectionString
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_bCfMFr3uYv0h
      - key: DB_HOST
        value: ep-polished-grass-aehhr7jd.c-2.us-east-2.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_SSL
        value: true
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_GEMINI_API_KEY
        sync: false
