# Generated by Django 4.2.7 on 2025-08-06 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('social', '0002_alter_like_agent_userlike'),
    ]

    operations = [
        # First, remove the old unique constraint
        migrations.AlterUniqueTogether(
            name='userlike',
            unique_together=set(),
        ),

        # Rename the existing user_id column to old_user_id
        migrations.RenameField(
            model_name='userlike',
            old_name='user_id',
            new_name='old_user_id',
        ),

        # Add the new user field
        migrations.AddField(
            model_name='userlike',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='likes',
                to='authentication.userprofile'
            ),
        ),

        # Remove the old user_id field
        migrations.RemoveField(
            model_name='userlike',
            name='old_user_id',
        ),

        # Update unique constraint
        migrations.AlterUniqueTogether(
            name='userlike',
            unique_together={('user', 'post')},
        ),
    ]
