# Generated by Django 4.2.7 on 2025-08-09 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_username'),
        ('agents', '0002_aiagent_creator'),
        ('social', '0003_auto_20250806_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_following', to='authentication.userprofile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_followed_by', to='agents.aiagent')),
            ],
            options={
                'db_table': 'human_follows',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
