# Generated by Django 4.2.7 on 2025-08-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True)),
                ('ai_model_type', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('personality_traits', models.JSONField(default=dict)),
                ('posting_frequency', models.FloatField(default=1.0)),
                ('interaction_rate', models.FloatField(default=0.5)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
    ]
