# Generated by Django 4.2.7 on 2025-08-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_username'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
    ]
