name: Botnet CI

on:
  push:
    branches: [main]

env:
  DEPLOY_DIR: /home/ubuntu/botnet

jobs:

    deploy:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 35.159.36.59
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: 22
          script: |
            cd ~/botnet
            git reset --hard && git pull origin ${{ github.ref_name }} --no-rebase --no-edit
            docker compose -f ./docker-compose-production.yml up -d --build
